---
- name: Check CVE vulnerabilities on RHEL 8
  hosts: uhartnonprodservers
  gather_facts: yes
  remote_user: root
  tasks:

    - name: Define CVEs being checked
      set_fact:
        cve_list: 
          - CVE-2024-36387
          - CVE-2024-38472
          - CVE-2024-38473
          - CVE-2024-38474
          - CVE-2024-38475
          - CVE-2024-38476
          - CVE-2024-38477
          - CVE-2024-39573
          - CVE-2022-1292
          - CVE-2022-2068

    - name: Check for CVE updates in dnf updateinfo
      shell: dnf updateinfo list | grep -E "{{ cve_list | join('|') }}"
      register: dnf_cve_check
      ignore_errors: yes

    - name: Check OpenSSL package changelog for vulnerabilities
      shell: rpm -q --changelog openssl | grep -i "CVE-2022-1292\|CVE-2022-2068" || true
      register: openssl_cve_check
      ignore_errors: yes

    - name: Check if HTTPD is installed
      command: rpm -q httpd
      register: httpd_installed
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Display message if HTTPD is not installed
      debug:
        msg: "ℹ️ HTTPD package is NOT installed on this server."
      when: httpd_installed.rc != 0

    - name: Check HTTPD package changelog for vulnerabilities
      shell: rpm -q --changelog httpd | grep -i "CVE-2024-38473\|CVE-2024-38476" || true
      register: httpd_cve_check
      when: httpd_installed.rc == 0
      ignore_errors: yes

    - name: Extract CVEs found in the system
      set_fact:
        found_cves: "{{ (dnf_cve_check.stdout_lines + openssl_cve_check.stdout_lines + (httpd_cve_check.stdout_lines if httpd_installed.rc == 0 else [])) | select('search', 'CVE-') | list }}"

    - name: Extract CVEs that were checked but not found
      set_fact:
        not_found_cves: "{{ cve_list | difference(found_cves | map('regex_search', 'CVE-[0-9]+-[0-9]+') | select('string') | list) }}"

    - name: Display checked CVEs
      debug:
        msg: 
          - "🔎 CVEs Checked: {{ cve_list | join(', ') }}"
          - "✅ CVEs NOT found in the system: {{ not_found_cves | join(', ') }}"
      when: not_found_cves | length > 0

    - name: Display CVEs found in the system
      debug:
        msg: "⚠️ The following CVEs were found on this system: {{ found_cves | join(', ') }}"
      when: found_cves | length > 0

    - name: Determine if the system is vulnerable
      set_fact:
        vulnerable: "{{ found_cves | length > 0 }}"

    - name: Display final vulnerability status
      debug:
        msg: "{{ '⚠️ System is VULNERABLE to at least one CVE! Apply patches ASAP!' if vulnerable else '✅ System is NOT vulnerable to the specified CVEs.' }}"

