---
- hosts: uhartprodservers
  gather_facts: yes
  remote_user: root

  tasks:
    - name: Clean package cache
      ansible.builtin.command: dnf clean all

    - name: Remove old kernels, keeping only the latest 2
      ansible.builtin.command: |
        package-cleanup --oldkernels --count=2
      ignore_errors: yes

    - name: Update all packages to the latest version on RHEL 8.10
      dnf:
        name: "*"
        state: latest
      become: yes
      become_user: root
      register: dnf_update_status

    - name: Reboot server if required
      reboot:
        msg: "Rebooting for kernel updates"
        reboot_timeout: 600
      when: dnf_update_status is changed
      become: yes
      become_user: root

    - name: Display the output that the system is patched
      debug:
        msg: "The system {{ inventory_hostname }} is successfully patched to the latest updates"
      when: dnf_update_status is changed
