---
- hosts: uhartnonprodservers
  gather_facts: yes
  remote_user: root
  tasks:
    
    - name: Get system uptime
      command: uptime -p
      register: uptime_result
      changed_when: false

    - name: Display uptime
      debug:
        msg: "Server has been up for: {{ uptime_result.stdout }}"
